"""Initial tenant isolated schema"""
from alembic import op
import sqlalchemy as sa

revision = '5d717c6e8e84'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=254), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_tenant_time', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')"),
    sa.CheckConstraint("status IN ('OPEN','INVESTIGATING','RESOLVED')"),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_tenant_filters', 'security_events', ['tenant_id', 'status', 'severity', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN','MANAGER','USER')"),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','COMPLETED','CANCELLED')"),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by'], ['users.tenant_id', 'users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id')
    )
    op.create_index('ix_campaigns_tenant_status', 'campaigns', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('campaign_members',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'campaign_id'], ['campaigns.tenant_id', 'campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['users.tenant_id', 'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'campaign_id', 'user_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_members')
    op.drop_index('ix_campaigns_tenant_status', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_events_tenant_filters', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_audit_tenant_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
