import { useEffect, useState } from 'react';
import { Activity, ArrowRight, Bell, ChevronDown, CircleHelp, LayoutDashboard, LogOut, Menu, Radio, Users, X, ListChecks, ScanLine } from 'lucide-react';
import { api, hasToken, setToken, write, type Tenant, type User } from './api';
import { Brand, ErrorBox, Loading, Modal } from './components';
import DashboardPage from './Dashboard';
import RecordsPage from './Records';
import Landing from './Landing';
import OrganizationForm, { type CreatedOrganization } from './OrganizationForm';

type Session = { user: User; tenant: Tenant };
export type View = 'overview'|'campaigns'|'events'|'users'|'audit';
const navigation = [{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'campaigns',label:'Campaigns',icon:Radio},{id:'events',label:'Security events',icon:Activity},{id:'users',label:'Team members',icon:Users},{id:'audit',label:'Audit logs',icon:ListChecks}] as const;

export default function App() {
  const [createOrganization,setCreateOrganization]=useState(false);const [newOrganization,setNewOrganization]=useState<CreatedOrganization|null>(null);
  const [session,setSession]=useState<Session|null>(null);const [loading,setLoading]=useState(hasToken());
  const [loggingOut,setLoggingOut]=useState(false);
  const [view,setView]=useState<View>('overview');const [mobile,setMobile]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{let active=true;const expire=()=>{setSession(null);setError('Your session ended. Please sign in again.');};window.addEventListener('session-expired',expire);if(hasToken()) api<Session>('/auth/me').then(s=>{if(active)setSession(s);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;window.removeEventListener('session-expired',expire);};},[]);
  async function logout(){if(loggingOut)return;setLoggingOut(true);setError('');try{await write('/auth/logout','POST');setToken('');setSession(null);setView('overview');setMobile(false);setCreateOrganization(false);setNewOrganization(null);}catch(e){setError((e as Error).message);}finally{setLoggingOut(false);}}
  function navigate(next:View){setView(next);setMobile(false);setError('');}
  if(loading) return <Loading/>;
  if(!session) return <><Landing onLogin={s=>{setSession(s);setView('overview');setError('');}}/>{error&&<div className="toast" role="status">{error}<button aria-label="Dismiss" onClick={()=>setError('')}><X size={15}/></button></div>}</>;
  return <div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}><Brand/><button className="workspace" onClick={()=>navigate('overview')}><span className="tenant-avatar">{session.tenant.name[0]}</span><span><b>{session.tenant.name}</b><small>Organization workspace</small></span><ChevronDown size={15}/></button><button className="add-organization" onClick={()=>{setNewOrganization(null);setCreateOrganization(true);}}>+ Create organization</button><span className="nav-label">WORKSPACE</span><nav>{navigation.filter(n=>n.id!=='audit'||session.user.role==='ADMIN').map(n=><button key={n.id} className={view===n.id?'selected':''} onClick={()=>navigate(n.id)}><n.icon size={19}/>{n.label}{view===n.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="security-status"><span className="pulse"/><div><b>Tenant isolation enabled</b><small>Access scoped to your organization</small></div></div><a href="http://localhost:8000/docs" target="_blank" rel="noreferrer"><CircleHelp size={18}/>API documentation<ArrowRight size={15}/></a><div className="profile"><span className="avatar">{session.user.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><span><b>{session.user.name}</b><small>{session.user.role.toLowerCase()}</small></span><button className="icon-button" title="Sign out of all sessions" aria-label="Sign out" disabled={loggingOut} onClick={logout}><LogOut size={17}/></button></div></div></aside>{mobile&&<button className="sidebar-overlay" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
  <div className="main-shell">{createOrganization&&<Modal title="Create another organization" onClose={()=>setCreateOrganization(false)}>{newOrganization?<div className="organization-created"><h3>{newOrganization.tenant.name} is ready.</h3><p>Organization ID: <b>{newOrganization.tenant.slug}</b></p><p>Your current workspace remains open. Sign out and use the new administrator credentials to access this organization.</p><button className="primary" onClick={()=>setCreateOrganization(false)}>Continue in current workspace</button></div>:<OrganizationForm onCreated={setNewOrganization}/>}</Modal>}<header className="topbar"><div><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={21}/></button><span>Workspace</span><span className="breadcrumb-slash">/</span><b>{navigation.find(n=>n.id===view)?.label}</b></div><div><span className="environment"><span className="pulse"/>LIVE WORKSPACE</span><button className="icon-button" aria-label="View security events" onClick={()=>navigate('events')}><Bell size={19}/></button><span className="top-avatar">{session.user.name[0]}</span><button className="logout-button" title="Sign out of all sessions" onClick={logout} disabled={loggingOut}><LogOut size={16}/>{loggingOut?'Signing out?':'Logout'}</button></div></header><main className="content"><ErrorBox message={error}/>{view==='overview'?<DashboardPage user={session.user} navigate={navigate}/>:<RecordsPage key={view} view={view} user={session.user}/>}<footer className="page-footer"><span><ScanLine size={15}/>Deep Trace Cybernetics</span><span>Security operations, in focus.</span></footer></main></div></div>;
}
