import { useEffect, useState } from 'react';
import { Activity, ArrowDownRight, ArrowRight, CalendarDays, ChevronRight, CircleAlert, Radio, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import { api, type Dashboard, type User } from './api';
import { Badge, Empty, ErrorBox, Loading, time } from './components';
import type { View } from './App';

export default function DashboardPage({user,navigate}: {user:User;navigate:(v:View)=>void}) {
  const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;setError('');api<Dashboard>('/dashboard').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[refresh]);
  if(!data) return error?<ErrorBox message={error}/>:<Loading/>;
  const max=Math.max(1,...data.trend.map(d=>d.count));const total=Object.values(data.severity_counts).reduce((a,b)=>a+b,0);
  const metrics=[{label:'Active team members',value:data.users,icon:Users,note:'Across your organization',className:'mint'}, {label:'Total campaigns',value:data.campaigns,icon:Radio,note:`${data.active_campaigns} currently active`,className:'blue'}, {label:'Open security events',value:data.open_events,icon:Activity,note:'Open and under investigation',className:'amber'},{label:'Critical alerts',value:data.critical_events,icon:CircleAlert,note:data.critical_events?'Require immediate attention':'No unresolved critical events',className:'red'}];
  return <><div className="page-heading"><div><span className="eyebrow">YOUR SECURITY COMMAND CENTER</span><h1>Workspace overview<span className="heading-dot">.</span></h1><p>Welcome back, {user.name.split(' ')[0]}. Here's your security landscape.</p></div><div className="heading-actions"><span className="date-chip"><CalendarDays size={16}/>{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span><button className="icon-button bordered" aria-label="Refresh dashboard" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={17}/></button></div></div><ErrorBox message={error}/>
  <div className="overview-banner"><div className="banner-icon"><ShieldCheck size={25}/></div><div><b>A clear view of your security posture.</b><p>{data.critical_events?`${data.critical_events} critical ${data.critical_events===1?'event needs':'events need'} your team's attention. Review and take action.`:'Stay ahead of threats. Monitor activity and keep your team aligned.'}</p></div><button onClick={()=>navigate('events')}>Review events<ArrowRight size={17}/></button></div>
  <div className="metrics">{metrics.map(m=><article className="metric" key={m.label}><div><span>{m.label}</span><span className={`metric-icon ${m.className}`}><m.icon size={19}/></span></div><strong>{m.value.toString().padStart(2,'0')}</strong><small><span className={`mini-dot ${m.className}`}/>{m.note}</small></article>)}</div>
  <div className="chart-grid"><section className="panel"><div className="panel-heading"><div><h2>Security event activity</h2><p>Events recorded over the last 7 days</p></div><span className="subtle-chip">Last 7 days</span></div><div className="chart"><div className="chart-scale">{[max,Math.round(max/2),0].map((n,i)=><span key={i}>{n}</span>)}</div><div className="bars">{data.trend.map((d,i)=><div className="bar-column" key={i}><span className="bar-count">{d.count}</span><div className={`bar ${i===6?'today':''}`} style={{height:`${Math.max(2,d.count/max*130)}px`}} title={`${d.day}: ${d.count} events`}/><span>{d.day}</span></div>)}</div></div><div className="chart-caption"><span><i/>Security events</span><span>{data.trend.reduce((s,d)=>s+d.count,0)} total this week</span></div></section><section className="panel severity-panel"><div className="panel-heading"><div><h2>Threat breakdown</h2><p>Unresolved events by severity</p></div><CircleAlert size={18}/></div><div className="severity-total"><strong>{total}</strong><span>unresolved events</span></div><div className="severity-stack">{Object.entries(data.severity_counts).map(([s,n])=><div key={s} className={s.toLowerCase()} style={{flex:n||0.02}} title={`${s}: ${n}`}/>)}</div><div className="severity-legend">{Object.entries(data.severity_counts).map(([s,n])=><div key={s}><span><i className={s.toLowerCase()}/>{s[0]+s.slice(1).toLowerCase()}</span><b>{n}</b></div>)}</div></section></div>
  <section className="panel"><div className="panel-heading"><div><h2>Recent security events</h2><p>The latest signals across your organization</p></div><button className="text-button" onClick={()=>navigate('events')}>View all events<ArrowRight size={16}/></button></div><div className="table-scroll"><table><thead><tr><th>EVENT</th><th>SEVERITY</th><th>STATUS</th><th>DETECTED</th><th/></tr></thead><tbody>{data.recent_events.map(e=><tr key={e.id}><td><div className="event-name"><span className={`event-icon ${e.severity.toLowerCase()}`}><Activity size={17}/></span><div><b>{e.event_type}</b><small>EVT-{String(e.id).padStart(4,'0')}</small></div></div></td><td><Badge value={e.severity}/></td><td><Badge value={e.status}/></td><td className="muted">{time(e.created_at)}</td><td><button className="icon-button" aria-label={`View ${e.event_type}`} onClick={()=>navigate('events')}><ChevronRight size={18}/></button></td></tr>)}</tbody></table>{!data.recent_events.length&&<Empty text="No security events recorded yet."/>}</div></section>
  <section className="campaign-preview"><div className="section-heading"><div><h2>{user.role==='USER'?'Your assigned campaigns':'Campaign spotlight'}</h2><p>Keep your security initiatives moving forward.</p></div><button className="text-button" onClick={()=>navigate('campaigns')}>All campaigns<ArrowRight size={16}/></button></div><div className="campaign-cards">{data.recent_campaigns.map(c=><button className="campaign-card" key={c.id} onClick={()=>navigate('campaigns')}><div><span className="campaign-symbol"><Radio size={20}/></span><Badge value={c.status}/></div><h3>{c.title}</h3><p>{c.description}</p><span className="card-link">Explore campaign<ArrowDownRight size={16}/></span></button>)}</div>{!data.recent_campaigns.length&&<Empty text="No campaigns available yet."/>}</section></>;
}
