import { useState, type FormEvent } from 'react';
import { Activity, ArrowDown, ArrowRight, Building2, Check, CheckCircle2, Eye, EyeOff, Fingerprint, Layers3, LockKeyhole, Radar, ShieldCheck, Users, X } from 'lucide-react';
import { setToken, write, type User, type Tenant } from './api';
import { Brand, ErrorBox, Modal } from './components';
import SecurityIllustration from './SecurityIllustration';
import OrganizationForm, { type CreatedOrganization } from './OrganizationForm';

type Session={user:User;tenant:Tenant};
export default function Landing({onLogin}:{onLogin:(session:Session)=>void}) {
  const [mode,setMode]=useState<'login'|'create'|null>(null);const [created,setCreated]=useState<CreatedOrganization|null>(null);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [visible,setVisible]=useState(false);
  function open(next:'login'|'create'){setError('');setMode(next);}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);try{const result=await write<Session&{access_token:string}>('/auth/login','POST',Object.fromEntries(new FormData(e.currentTarget)));setToken(result.access_token);onLogin(result);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="cyber-page"><div className="cyber-frame"><header className="cyber-header"><a href="#home" aria-label="Deep Trace Cybernetics home"><Brand/></a><nav aria-label="Main navigation"><a href="#platform">Platform</a><a href="#capabilities">Capabilities</a><a href="#how-it-works">How it works</a></nav><div className="cyber-header-actions"><button className="cyber-signin" onClick={()=>open('login')}>Sign in<ArrowRight size={15}/></button><button className="cyber-button compact" onClick={()=>open('create')}>Create organization</button></div></header>
  <main><section className="cyber-hero" id="home"><div className="hero-copy"><span className="cyber-eyebrow"><span/>SECURITY STARTS WITH VISIBILITY</span><h1 className="hero-title"><span>Your security operations.</span><span>One trusted workspace.</span></h1><p>Coordinate your team, manage security campaigns, and track critical events with Deep Trace Cybernetics. Clear visibility for every organization.</p><div className="hero-actions"><button className="cyber-button" onClick={()=>open('create')}>Get started<ArrowRight size={18}/></button><button className="cyber-outline" onClick={()=>open('login')}>Sign in<Layers3 size={17}/></button></div><div className="hero-assurance"><span><Check size={14}/>Isolated workspaces</span><span><Check size={14}/>Role-based access</span><span><Check size={14}/>Traceable actions</span></div></div>
  <div className="security-visual"><SecurityIllustration/></div></section>
  <div className="platform-strip" id="platform"><span>ONE PLATFORM.<br/><b>A CLEARER PICTURE.</b></span><div><Building2/>Organization isolation</div><div><Users/>Team permissions</div><div><Radar/>Security operations</div><div><ShieldCheck/>Audit visibility</div></div>
  <section className="cyber-capabilities" id="capabilities"><div className="capability-intro"><span className="cyber-eyebrow">BUILT FOR YOUR EVERYDAY DEFENSE</span><h2>Complex threats.<br/><span>Clearer operations.</span></h2><p>Less switching between tools. More clarity for the people keeping your organization secure.</p><a href="#how-it-works">See how it comes together<ArrowDown size={16}/></a></div><div className="capability-grid">{[{icon:Layers3,title:'Turn plans into action',text:'Create campaigns, assign your team, and track each initiative from draft to completion.',number:'01'},{icon:Activity,title:'Put signals in context',text:'Record security events, prioritize severity, and follow investigations through resolution.',number:'02'},{icon:Users,title:'Give every role its place',text:'Bring admins, managers, and users together with clearly defined permissions.',number:'03'},{icon:ShieldCheck,title:'Keep a trace of every move',text:'Review important actions with tenant-scoped audit history and accountable operations.',number:'04'}].map(c=><article key={c.number}><div><span className="capability-icon"><c.icon size={22}/></span><small>{c.number}</small></div><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
  <section className="cyber-steps" id="how-it-works"><div><span className="cyber-eyebrow">FROM SETUP TO SECURITY</span><h2>Your workspace.<br/>Ready for your team.</h2></div><ol><li><span>01</span><div><h3>Create your organization</h3><p>Choose a name and a unique organization ID. Set up your first administrator.</p></div></li><li><span>02</span><div><h3>Bring the right people in</h3><p>Add team members, define their roles, and assign campaign responsibilities.</p></div></li><li><span>03</span><div><h3>Get a clearer view</h3><p>Track campaigns, investigate events, and review activity from your console.</p></div></li></ol></section>
  <section className="cyber-cta"><div><span className="cyber-eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>A stronger security workflow.<br/>A workspace of your own.</h2></div><button className="cyber-button" onClick={()=>open('create')}>Create your organization<ArrowRight size={18}/></button></section></main><footer className="cyber-footer"><Brand/><span>Clarity in every signal. Confidence in every action.</span><small>© {new Date().getFullYear()} Deep Trace Cybernetics</small></footer></div>
  {mode&&<div className="cyber-dialog-theme"><Modal title={mode==='create'?'Create your organization':'Welcome to your workspace'} onClose={()=>{if(!busy)setMode(null);}}>{mode==='create'?<><p className="auth-intro">One organization. Your team. A dedicated place to manage security.</p><OrganizationForm onCreated={result=>{setCreated(result);setMode('login');setError('');}}/><p className="auth-switch">Already have a workspace? <button onClick={()=>open('login')}>Sign in</button></p></>:<>{created&&<div className="created-notice" role="status"><CheckCircle2 size={20}/><div><b>{created.tenant.name} is ready.</b><span>Organization ID: <strong>{created.tenant.slug}</strong>. Sign in below to get started.</span></div><button aria-label="Dismiss" onClick={()=>setCreated(null)}><X size={15}/></button></div>}<p className="auth-intro">Sign in with your organization ID and team credentials.</p><form onSubmit={login} className="onboarding-form"><label>Organization ID<input key={created?.tenant.slug||'org'} name="organization" defaultValue={created?.tenant.slug} placeholder="e.g. acme" autoComplete="organization" required maxLength={80} autoCapitalize="none"/><small>Enter your workspace ID, not the company display name.</small></label><label>Email address<input key={created?.email||'email'} name="email" type="email" defaultValue={created?.email} placeholder="you@company.com" autoComplete="username" required maxLength={254}/></label><label>Password<div className="password-input"><input name="password" type={visible?'text':'password'} autoComplete="current-password" required maxLength={128} placeholder="Enter your password"/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><ErrorBox message={error}/><button className="cyber-button full" disabled={busy}>{busy?'Signing in…':'Sign in to workspace'}<ArrowRight size={17}/></button></form><p className="auth-switch">New to Deep Trace? <button onClick={()=>open('create')}>Create organization</button></p><details className="auth-demo"><summary>Try a demo workspace</summary><p>ID: <b>acme</b> · Email: <b>admin@acme.test</b><br/>Password: <b>DemoPassword123!</b></p></details></>}</Modal></div>}</div>;
}
